#!/bin/sh

# This POC script is (intentionally) overly trivial.
# a TODO future PRODUCTION version of this would probably want tomake it possible to
# e.g. pass additional parameters to the executable, as does fabric8io-images/s2i's run script.

if [ -z "$QUARKUS_OPTS" ]; then
  QUARKUS_OPTS="-Xmx12M -Xms8M -Xmn12M"
  echo "QUARKUS_OPTS environment variable was not set, using default values of ${QUARKUS_OPTS}"
else
  echo "Using custom Java opts from environment QUARKUS_OPTS=${QUARKUS_OPTS}"
fi

exec /opt/quarkus/application ${QUARKUS_OPTS} -Dquarkus.http.host=0.0.0.0